#!/bin/bash

echo "🔐 OAuth Setup for InfraMind"
echo "=============================="
echo ""

echo "📋 To enable social login, you need to configure OAuth providers:"
echo ""

echo "🌐 Google OAuth Setup:"
echo "1. Go to https://console.developers.google.com/"
echo "2. Create a new project or select existing one"
echo "3. Enable Google+ API"
echo "4. Go to Credentials → Create Credentials → OAuth 2.0 Client IDs"
echo "5. Set Application Type to 'Web application'"
echo "6. Add Authorized redirect URIs:"
echo "   - http://localhost:8080/auth/callback"
echo "   - http://localhost:3000/auth/callback"
echo "7. Copy Client ID and Client Secret"
echo ""

echo "🐙 GitHub OAuth Setup:"
echo "1. Go to https://github.com/settings/developers"
echo "2. Click 'New OAuth App'"
echo "3. Set Application name: InfraMind"
echo "4. Set Homepage URL: http://localhost:8080"
echo "5. Set Authorization callback URL: http://localhost:8080/auth/callback"
echo "6. Copy Client ID and Client Secret"
echo ""

echo "📝 Add these environment variables to your .env file:"
echo ""
echo "# OAuth Configuration"
echo "GOOGLE_CLIENT_ID=your-google-client-id"
echo "GOOGLE_CLIENT_SECRET=your-google-client-secret"
echo "GITHUB_CLIENT_ID=your-github-client-id"
echo "GITHUB_CLIENT_SECRET=your-github-client-secret"
echo "OAUTH_REDIRECT_URI=http://localhost:8080/auth/callback"
echo ""

echo "✅ After configuring, restart the AI services to apply changes."
echo ""
echo "🔗 Test URLs:"
echo "- Google OAuth: http://localhost:8001/auth/oauth/google?redirect_uri=http://localhost:8080/auth/callback"
echo "- GitHub OAuth: http://localhost:8001/auth/oauth/github?redirect_uri=http://localhost:8080/auth/callback" 