apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-services
  namespace: ai-ops-production
  labels:
    app: ai-services
    version: IMAGE_TAG
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-services
  template:
    metadata:
      labels:
        app: ai-services
        version: IMAGE_TAG
    spec:
      containers:
      - name: ai-services
        image: ghcr.io/your-org/ai-ops-guardian-angel/ai-services:IMAGE_TAG
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: ai-ops-config
        - secretRef:
            name: ai-ops-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: ai-services-service
  namespace: ai-ops-production
spec:
  selector:
    app: ai-services
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
  type: ClusterIP 