// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhtcjrufsnkgqwcmfvnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpodGNqcnVmc25rZ3F3Y21mdm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTQ1NjksImV4cCI6MjA1OTU5MDU2OX0.gPPD6o9UU0U0LO6wgZstbAiAN90Y_nT3vz0fHxNsdsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);