name: ChatOps - Cloud Operations

on:
  workflow_dispatch:
    inputs:
      provider:
        description: "Cloud provider (aws)"
        required: true
        type: choice
        options: [aws]
      action:
        description: "Action (inventory|instance_start|instance_stop|instance_reboot|instance_resize|sg_authorize|sg_revoke|ebs_snapshot|dns_upsert|cdn_invalidate)"
        required: true
      region:
        description: "Region (e.g., us-east-1)"
        required: true
      params:
        description: "JSON-encoded parameters for the action"
        required: false
        default: "{}"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        if: ${{ github.event.inputs.provider == 'aws' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Parse params
        id: p
        run: |
          echo "params=${{ github.event.inputs.params }}" > params.json
          cat params.json

      - name: Execute AWS action
        if: ${{ github.event.inputs.provider == 'aws' }}
        env:
          ACTION: ${{ github.event.inputs.action }}
          REGION: ${{ github.event.inputs.region }}
        run: |
          set -euo pipefail
          PARAMS=$(cat params.json)
          get_param() { echo "$PARAMS" | jq -r .$1; }
          case "$ACTION" in
            inventory)
              aws ec2 describe-instances --query 'Reservations[].Instances[].{Id:InstanceId,Type:InstanceType,State:State.Name,AZ:Placement.AvailabilityZone,Name:Tags[?Key==`Name`].Value|[0]}' --output table | tee inventory.txt
              ;;
            instance_start)
              IDS=$(get_param instance_ids | jq -r 'join(" ")')
              aws ec2 start-instances --instance-ids $IDS | tee op.txt
              ;;
            instance_stop)
              IDS=$(get_param instance_ids | jq -r 'join(" ")')
              aws ec2 stop-instances --instance-ids $IDS | tee op.txt
              ;;
            instance_reboot)
              IDS=$(get_param instance_ids | jq -r 'join(" ")')
              aws ec2 reboot-instances --instance-ids $IDS | tee op.txt
              ;;
            instance_resize)
              ID=$(get_param instance_id)
              TYPE=$(get_param instance_type)
              aws ec2 modify-instance-attribute --instance-id "$ID" --instance-type "\"$TYPE\"" | tee op.txt
              ;;
            sg_authorize)
              SG=$(get_param sg_id); PROTO=$(get_param protocol); FP=$(get_param from_port); TP=$(get_param to_port); CIDR=$(get_param cidr)
              aws ec2 authorize-security-group-ingress --group-id "$SG" --ip-permissions IpProtocol=$PROTO,FromPort=$FP,ToPort=$TP,IpRanges="[{CidrIp=$CIDR}]" | tee op.txt
              ;;
            sg_revoke)
              SG=$(get_param sg_id); PROTO=$(get_param protocol); FP=$(get_param from_port); TP=$(get_param to_port); CIDR=$(get_param cidr)
              aws ec2 revoke-security-group-ingress --group-id "$SG" --ip-permissions IpProtocol=$PROTO,FromPort=$FP,ToPort=$TP,IpRanges="[{CidrIp=$CIDR}]" | tee op.txt
              ;;
            ebs_snapshot)
              VOL=$(get_param volume_id); DESC=$(get_param description)
              aws ec2 create-snapshot --volume-id "$VOL" --description "$DESC" | tee op.txt
              ;;
            dns_upsert)
              ZONE=$(get_param zone_id); NAME=$(get_param name); RTYPE=$(get_param rtype); VALUE=$(get_param value); TTL=$(get_param ttl)
              cat > change-batch.json <<JSON
              {"Changes":[{"Action":"UPSERT","ResourceRecordSet":{"Name":"$NAME","Type":"$RTYPE","TTL":${TTL:-60},"ResourceRecords":[{"Value":"$VALUE"}]}}]}
JSON
              aws route53 change-resource-record-sets --hosted-zone-id "$ZONE" --change-batch file://change-batch.json | tee op.txt
              ;;
            cdn_invalidate)
              DIST=$(get_param distribution_id); PATHS=$(get_param paths | jq -c .)
              aws cloudfront create-invalidation --distribution-id "$DIST" --paths $(echo $PATHS | jq -r 'join(" ")') | tee op.txt
              ;;
            *)
              echo "Unsupported action: $ACTION"; exit 1;
              ;;
          esac

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: cloud-ops-output
          path: |
            *.txt
            inventory.txt
            op.txt


