name: Tag Remediation

on:
  workflow_dispatch:
    inputs:
      tenant_id:
        description: 'Tenant ID for tag remediation'
        required: true
        type: string
      auto_remediate:
        description: 'Automatically fix tag violations'
        required: false
        type: boolean
        default: true
      dry_run:
        description: 'Dry run mode (no actual changes)'
        required: false
        type: boolean
        default: true
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC
  repository_dispatch:
    types: [tag_remediation]

env:
  PYTHON_VERSION: '3.11'
  REMEDIATION_TIMEOUT: 900  # 15 minutes

jobs:
  scan-tag-violations:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo motor pydantic
          
      - name: Run tag violation scan
        env:
          TENANT_ID: ${{ github.event.inputs.tenant_id || 'default' }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          python scripts/policy/scan_tag_violations.py
          
      - name: Upload scan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tag-scan-${{ github.run_id }}
          path: |
            tag_scan_logs/
            *.json
            *.log

  generate-remediation-plan:
    needs: [scan-tag-violations]
    if: always() && needs.scan-tag-violations.result == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo motor pydantic jinja2
          
      - name: Download scan artifacts
        uses: actions/download-artifact@v4
        with:
          name: tag-scan-${{ github.run_id }}
          
      - name: Generate remediation plan
        env:
          TENANT_ID: ${{ github.event.inputs.tenant_id || 'default' }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          python scripts/policy/generate_remediation_plan.py
          
      - name: Upload remediation plan
        uses: actions/upload-artifact@v4
        with:
          name: remediation-plan-${{ github.run_id }}
          path: |
            remediation_plans/
            *.json
            *.html
            *.log

  policy-validation:
    needs: [generate-remediation-plan]
    if: always() && needs.generate-remediation_plan.result == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install conftest
          
      - name: Download remediation plan
        uses: actions/download-artifact@v4
        with:
          name: remediation-plan-${{ github.run_id }}
          
      - name: Run OPA policy validation
        run: |
          # Install conftest
          curl -L -o conftest https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_linux_x86_64.tar.gz
          tar -xzf conftest_linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          
          # Run policy validation
          conftest test -p policies/opa/tags remediation_plans/ --output json > policy_results.json
          
      - name: Upload policy validation results
        uses: actions/upload-artifact@v4
        with:
          name: policy-validation-${{ github.run_id }}
          path: |
            policy_results.json
            remediation_plans/

  approval-gate:
    needs: [policy-validation]
    if: always() && needs.policy-validation.result == 'success' && github.event.inputs.auto_remediate == 'false'
    runs-on: ubuntu-latest
    environment: tag-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-${{ github.run_id }}'
          merge-multiple: true
          
      - name: Generate approval summary
        run: |
          python scripts/policy/generate_approval_summary.py
          
      - name: Upload approval summary
        uses: actions/upload-artifact@v4
        with:
          name: approval-summary-${{ github.run_id }}
          path: |
            approval_summaries/
            *.html
            *.json

  execute-remediation:
    needs: [policy-validation, approval-gate]
    if: always() && needs.policy-validation.result == 'success' && (github.event.inputs.auto_remediate == 'true' || needs.approval-gate.result == 'success')
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo motor pydantic
          
      - name: Download remediation plan
        uses: actions/download-artifact@v4
        with:
          name: remediation-plan-${{ github.run_id }}
          
      - name: Execute tag remediation
        env:
          TENANT_ID: ${{ github.event.inputs.tenant_id || 'default' }}
          DRY_RUN: ${{ github.event.inputs.dry_run || true }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          python scripts/policy/execute_remediation.py
          
      - name: Upload execution results
        uses: actions/upload-artifact@v4
        with:
          name: remediation-execution-${{ github.run_id }}
          path: |
            execution_logs/
            *.json
            *.log

  generate-final-report:
    needs: [execute-remediation]
    if: always() && needs.execute-remediation.result == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo motor pydantic jinja2
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-${{ github.run_id }}'
          merge-multiple: true
          
      - name: Generate final report
        env:
          TENANT_ID: ${{ github.event.inputs.tenant_id || 'default' }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          python scripts/policy/generate_final_report.py
          
      - name: Upload final report
        uses: actions/upload-artifact@v4
        with:
          name: final-report-${{ github.run_id }}
          path: |
            final_reports/
            *.html
            *.json
            *.log

  notify-completion:
    needs: [scan-tag-violations, generate-remediation-plan, policy-validation, execute-remediation, generate-final-report]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Download final report
        uses: actions/download-artifact@v4
        with:
          name: final-report-${{ github.run_id }}
          
      - name: Send completion notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
        run: |
          python scripts/policy/notify_remediation_completion.py
          
      - name: Comment on PR if triggered by PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const reportPath = 'final_reports/tag_remediation_summary.json';
            
            if (fs.existsSync(reportPath)) {
              const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
              const comment = `## Tag Remediation Complete ✅
              
              **Tenant:** ${report.tenant_id}
              **Resources Scanned:** ${report.resources_scanned}
              **Tag Violations Found:** ${report.total_violations}
              **Auto-Remediated:** ${report.auto_remediated}
              **Manual Remediation Needed:** ${report.manual_remediation_needed}
              **Compliance Score:** ${report.compliance_score}%
              
              [View Full Report](${report.report_url})
              [View Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
